/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contenidoInventario;

import RegistroYLogueo.Home;
import com.mycompany.inventario.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Marca;
import persistencia.Dao;

/**
 *
 * @author mario
 */
public class MarcaFrm extends javax.swing.JFrame {

    /**
     * Creates new form MarcaFrm
     */
    Dao dao=new Dao();
    Conexion enlace=new Conexion();
    Connection conect=Conexion.getConexion();
     DefaultTableModel defualt=new DefaultTableModel();
    public MarcaFrm() {
        initComponents();
       rellenarTablaMarca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIntroduccion = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        miTablaMarca = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIntroduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntroduccion.setText("MARCA");
        jPanel1.add(lblIntroduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 81, 24));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodigo.setText("CODIGO");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, 20));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 177, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setText("NOMBRE");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 80, 20));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 177, -1));

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 120, 31));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar (1).png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 120, 31));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar (1).png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 120, 30));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 110, 31));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 13, 90, 75));

        miTablaMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Nombre"
            }
        ));
        miTablaMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miTablaMarcaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(miTablaMarca);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 551, 102));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 100, 30));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 352, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed

        String codigo=txtCodigo.getText();
        String nombre=txtNombre.getText();
        Marca marca=new Marca(codigo,nombre);
        if(codigo.isEmpty() || nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            dao.añadirMarca(marca);
       limpiar();
       vaciarTabla();
       rellenarTablaMarca();
       limpiar();
       txtCodigo.setEnabled(true);
        }
       
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
          int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres salir de la ventana marca?","Marca",JOptionPane.OK_CANCEL_OPTION);
        switch(opcion){
            case 0:System.out.println("Presionaste el boton aceptar");
          this.setVisible(false);
        Home home=new Home();
        home.setVisible(true);
        break;
            case 1: System.out.println("Presionaste el boton cancelar");
            break;
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila=miTablaMarca.getSelectedRow();
        Marca marca=new Marca();
        marca.setCodigoMarca(txtCodigo.getText());
        marca.setNombre(txtNombre.getText());
        if(txtCodigo.getText().isEmpty() || txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Losiento, no puede modificar, seleccione la seccion", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            if(dao.updateDatosMarca(marca)){
            limpiar();
            vaciarTabla();
            rellenarTablaMarca();
            limpiar();
       txtCodigo.setEnabled(true);
        }
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void miTablaMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miTablaMarcaMouseClicked
         miTablaMarca.getSelectedRow();
       String codigo=defualt.getValueAt(miTablaMarca.getSelectedRow(), 0).toString();
       txtCodigo.setText(codigo);
        txtCodigo.setEnabled(false);
        txtCodigo.setEditable(false);
       String nombre=defualt.getValueAt(miTablaMarca.getSelectedRow(), 1).toString();
       txtNombre.setText(nombre);
    }//GEN-LAST:event_miTablaMarcaMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila=miTablaMarca.getSelectedRow();
       Marca marca=new Marca();
       if(fila<0){
             JOptionPane.showMessageDialog(null, "Seleccione fila");
       }else{
           System.out.println(miTablaMarca.getValueAt(miTablaMarca.getSelectedRow(), 0).toString());
           if(dao.eliminarMarca(miTablaMarca.getValueAt(miTablaMarca.getSelectedRow(), 0).toString())){
               limpiar();
               vaciarTabla();
              rellenarTablaMarca();
              limpiar();
       txtCodigo.setEnabled(true);
            
           }
       }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void buscar(String buscar){
        DefaultTableModel modelo=dao.buscarCodigoMarca(buscar);
        miTablaMarca.setModel(modelo);
        txtBuscar.setText("");
    }
    
     public void rellenarTablaMarca(){
 
           
             defualt.addColumn("Codigo");
             defualt.addColumn("Nombre");
            miTablaMarca.setModel(defualt);
            
            String []datos=new String[2];
            try{
                Statement leer=conect.createStatement();
                ResultSet resultado=leer.executeQuery("SELECT * FROM marca");
                
                while(resultado.next()){
                    datos[0]=resultado.getString(1);
                    datos[1]=resultado.getString(2);
                    defualt.addRow(datos);
                }
                miTablaMarca.setModel(defualt);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
     
    }
      
     public void vaciarTabla(){
         while (defualt.getRowCount() > 0) {
            defualt.removeRow(0);
       }
        while(defualt.getColumnCount()>0){
     defualt.setColumnCount(defualt.getColumnCount() - 1);
        }
     }
     
     public void limpiar(){
        txtCodigo.setText("");
        txtNombre.setText("");
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarcaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarcaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarcaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarcaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarcaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblIntroduccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable miTablaMarca;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
