/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contenidoInventario;


import RegistroYLogueo.Home;
import com.mycompany.inventario.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Proveedor;
import persistencia.Dao;

/**
 *
 * @author mario
 */
public class ProveedorFrm extends javax.swing.JFrame {

    /**
     * Creates new form Proveedor
     */
    Dao dao=new Dao();
    Conexion enlace=new Conexion();
    Connection conect=Conexion.getConexion();
    DefaultTableModel defualt=new DefaultTableModel();
    public ProveedorFrm() {
        initComponents();
        rellenarTablaProveedor();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblPoblacion = new javax.swing.JLabel();
        txtProvincia = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        miTabaProveedor = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(72, 22));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PROVEEDOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 124, 28));

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDni.setText("DNI");
        jPanel1.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 69, 25));
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 120, -1));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodigo.setText("CODIGO");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 85, 25));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 130, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setText("NOMBRE");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 68, 25));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 130, -1));

        lblProvincia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblProvincia.setText("PROVINCIA");
        jPanel1.add(lblProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 76, 25));
        jPanel1.add(txtPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 120, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("E-MAIL");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 25));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 130, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefono.setText("TELÉFONO");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 85, 25));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 120, -1));

        lblPoblacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPoblacion.setText("POBLACIÓN");
        jPanel1.add(lblPoblacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 229, 76, 25));
        jPanel1.add(txtProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 130, -1));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDireccion.setText("DIRECCIÓN");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 176, 76, 25));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 177, 120, -1));

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 120, 31));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar (1).png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 120, 31));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                btnBuscarAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 120, 31));

        miTabaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "E-mail", "DNI", "Direccion", "Telefono", "Poblacion", "Provincia"
            }
        ));
        miTabaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miTabaProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(miTabaProveedor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 682, 127));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setPreferredSize(new java.awt.Dimension(490, 494));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 110, 31));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 170, 30));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar (1).png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 120, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String codigo=txtCodigo.getText();
        String dni=txtDni.getText();
        String nombre=txtNombre.getText();
        String telefono=txtTelefono.getText();
        String email=txtEmail.getText();
        String direccion=txtDireccion.getText();
        String provincia=txtProvincia.getText();
        String poblacion=txtPoblacion.getText();
        Proveedor proveedor=new Proveedor(codigo, dni, nombre, telefono, email, direccion, provincia, poblacion);
        if(codigo.isEmpty() || dni.isEmpty() || nombre.isEmpty() || telefono.isEmpty() || email.isEmpty() || direccion.isEmpty() || poblacion.isEmpty() || provincia.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            dao.añadirProveedor(proveedor);
        limpiar();
        vaciarTabla();
        rellenarTablaProveedor();
        limpiar();
       txtCodigo.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //JOptionPane.showMessageDialog(null, "Saliendo de la ventana proveedor");
         int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres salir de la ventana proveedor?","Proveedor",JOptionPane.OK_CANCEL_OPTION);
        switch(opcion){
            case 0:System.out.println("Presionaste el boton aceptar");
          this.setVisible(false);
        Home home=new Home();
        home.setVisible(true);
        break;
            case 1: System.out.println("Presionaste el boton cancelar");
            break;
        }
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila=miTabaProveedor.getSelectedRow();
        Proveedor pro=new Proveedor();
        pro.setCodigo(txtCodigo.getText());
       
        pro.setNombre(txtNombre.getText());
        pro.setEmail(txtEmail.getText());
        pro.setDni(txtDni.getText());
       
        pro.setDireccion(txtDireccion.getText());
        pro.setTelefono(txtTelefono.getText());
        pro.setPoblacion(txtPoblacion.getText());
        pro.setProvincia(txtProvincia.getText());
        if(txtCodigo.getText().isEmpty() || txtDni.getText().isEmpty() || txtNombre.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtEmail.getText().isEmpty() || txtDireccion.getText().isEmpty() || txtPoblacion.getText().isEmpty() || txtProvincia.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Losiento, no puede modificar, seleccione la seccion", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            if(dao.updateDatosProveedor(pro)){
            limpiar();
            vaciarTabla();
            rellenarTablaProveedor();
            limpiar();
       txtCodigo.setEnabled(true);
           
        }
        }
        
    
       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       buscar(txtBuscar.getText());
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void miTabaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miTabaProveedorMouseClicked
       miTabaProveedor.getSelectedRow();
       String codigo=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 0).toString();
       txtCodigo.setText(codigo);
        txtCodigo.setEnabled(false);
        txtCodigo.setEditable(false);
       String nombre=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 1).toString();
       txtNombre.setText(nombre);
       String email=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 2).toString();
       txtEmail.setText(email);
        String DNI=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 3).toString();
       txtDni.setText(DNI);
       /* txtDni.setEnabled(false);
        txtDni.setEditable(false);*/
        String direccion=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 4).toString();
       txtDireccion.setText(direccion);
        String telefono=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 5).toString();
       txtTelefono.setText(telefono);
        String poblacion=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 6).toString();
       txtPoblacion.setText(poblacion);
        String provincia=defualt.getValueAt(miTabaProveedor.getSelectedRow(), 7).toString();
       txtProvincia.setText(provincia);
    }//GEN-LAST:event_miTabaProveedorMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int fila=miTabaProveedor.getSelectedRow();
       Proveedor proveedor=new Proveedor();
       if(fila<0){
             JOptionPane.showMessageDialog(null, "Seleccione fila");
       }else{
           System.out.println(miTabaProveedor.getValueAt(miTabaProveedor.getSelectedRow(), 0).toString());
          if(dao.eliminarProveedor(miTabaProveedor.getValueAt(miTabaProveedor.getSelectedRow(), 0).toString())){
              limpiar();
              vaciarTabla();
              rellenarTablaProveedor();
              limpiar();
       txtCodigo.setEnabled(true);
              
              
          }
       }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnBuscarAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAncestorMoved

    public void buscar(String buscar){
        DefaultTableModel modelo=dao.buscarCodigoProveedor(buscar);
        miTabaProveedor.setModel(modelo);
        txtBuscar.setText("");
    }
    
    
    public void rellenarTablaProveedor(){
 
            
             defualt.addColumn("Codigo");
             defualt.addColumn("Nombre");
             defualt.addColumn("E-mail");
             defualt.addColumn("DNI");
             defualt.addColumn("Direccion");
             defualt.addColumn("Telefono");
             defualt.addColumn("Poblacion");
             defualt.addColumn("Provincia");
            miTabaProveedor.setModel(defualt);
            
            String []datos=new String[8];
            try{
                Statement leer=conect.createStatement();
                ResultSet resultado=leer.executeQuery("SELECT * FROM proveedor");
                
                while(resultado.next()){
                    datos[0]=resultado.getString(1);
                    datos[1]=resultado.getString(2);
                    datos[2]=resultado.getString(3);
                    datos[3]=resultado.getString(4);
                    datos[4]=resultado.getString(5);
                    datos[5]=resultado.getString(6);
                    datos[6]=resultado.getString(7);
                    datos[7]=resultado.getString(8);
                    defualt.addRow(datos);
                }
                miTabaProveedor.setModel(defualt);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
     
    }
    public void vaciarTabla(){
         while (defualt.getRowCount() > 0) {
            defualt.removeRow(0);
       }
        while(defualt.getColumnCount()>0){
     defualt.setColumnCount(defualt.getColumnCount() - 1);
        }
     }
    public void limpiar(){
        txtCodigo.setText("");
        txtNombre.setText("");
        txtEmail.setText("");
        txtDni.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtPoblacion.setText("");
        txtProvincia.setText("");
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveedorFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTable miTabaProveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtProvincia;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
