/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contenidoInventario;

import RegistroYLogueo.Home;
import com.mycompany.inventario.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Marca;
import modelo.Seccion;
import persistencia.Dao;

/**
 *
 * @author mario
 */
public class SeccionFrm extends javax.swing.JFrame {

    /**
     * Creates new form Seccion
     */
    Dao dao=new Dao();
    Conexion enlace=new Conexion();
    Connection conect=Conexion.getConexion();
    DefaultTableModel defualt=new DefaultTableModel();
    public SeccionFrm() {
        initComponents();
       rellenarTablaSeccion();
       //this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIntroduccion = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        miTablaSeccion = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIntroduccion.setBackground(new java.awt.Color(255, 255, 255));
        lblIntroduccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIntroduccion.setText("SECCIÓN");
        jPanel1.add(lblIntroduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 102, -1));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodigo.setText("CODIGO");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 73, 20));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 157, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombre.setText("NOMBRE");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 73, 20));
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 159, -1));

        lblColor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblColor.setText("Color");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 73, 20));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 157, -1));

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 120, 31));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar (1).png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 120, 31));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar (1).png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 120, 31));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 100, 31));

        miTablaSeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Color"
            }
        ));
        miTablaSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miTablaSeccionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(miTablaSeccion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 610, 110));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 120, 30));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String codigoSeccion=txtCodigo.getText();
        String nombre=txtNombre.getText();
        String color=txtColor.getText();
        Seccion seccion=new Seccion(codigoSeccion, nombre, color);
        if(codigoSeccion.isEmpty() || nombre.isEmpty() || color.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
        dao.añadirSeccion(seccion);
        limpiar();
        vaciarTabla();
        rellenarTablaSeccion();
        limpiar();
       txtCodigo.setEnabled(true);
        }
       
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //JOptionPane.showMessageDialog(null, "Saliendo de la ventana seccion");
         int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres salir de la ventana sección?","Sección",JOptionPane.OK_CANCEL_OPTION);
        switch(opcion){
            case 0:System.out.println("Presionaste el boton aceptar");
          this.setVisible(false);
        Home home=new Home();
        home.setVisible(true);
        break;
            case 1: System.out.println("Presionaste el boton cancelar");
            break;
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila=miTablaSeccion.getSelectedRow();
        Seccion seccion=new Seccion();
        seccion.setCodigoSeccion(txtCodigo.getText());
        seccion.setNombre(txtNombre.getText());
        seccion.setColor(txtColor.getText());
        if(txtCodigo.getText().isEmpty() || txtNombre.getText().isEmpty() || txtColor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Losiento, no puede modificar, seleccione la seccion", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            if(dao.updateDatosSeccion(seccion)){
            limpiar();
            vaciarTabla();
            rellenarTablaSeccion();
          limpiar();
       txtCodigo.setEnabled(true);
        }
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void miTablaSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miTablaSeccionMouseClicked
       miTablaSeccion.getSelectedRow();
       String codigo=defualt.getValueAt(miTablaSeccion.getSelectedRow(), 0).toString();
       txtCodigo.setText(codigo);
        txtCodigo.setEnabled(false);
        txtCodigo.setEditable(false);
       String nombre=defualt.getValueAt(miTablaSeccion.getSelectedRow(), 1).toString();
       txtNombre.setText(nombre);
       String color=defualt.getValueAt(miTablaSeccion.getSelectedRow(), 2).toString();
       txtColor.setText(color);
    }//GEN-LAST:event_miTablaSeccionMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
       int fila=miTablaSeccion.getSelectedRow();
       Seccion seccion=new Seccion();
       if(fila<0){
             JOptionPane.showMessageDialog(null, "Seleccione fila");
       }else{
            if(txtCodigo.getText().isEmpty() || txtNombre.getText().isEmpty() || txtColor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Losiento, no puede modificar, seleccione la seccion", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
               System.out.println(miTablaSeccion.getValueAt(miTablaSeccion.getSelectedRow(), 0).toString());
           if(dao.eliminarSeccion(miTablaSeccion.getValueAt(miTablaSeccion.getSelectedRow(), 0).toString())){
               limpiar();
               vaciarTabla();
              rellenarTablaSeccion();
              limpiar();
       txtCodigo.setEnabled(true);
              
           } 
            }
           
       }
    }//GEN-LAST:event_btnBorrarActionPerformed

    public void buscar(String buscar){
        DefaultTableModel modelo=dao.buscarCodigoSeccion(buscar);
        miTablaSeccion.setModel(modelo);
        txtBuscar.setText("");
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar(txtBuscar.getText());
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
      // buscarProducto();
    }//GEN-LAST:event_txtBuscarKeyReleased

    
      public void rellenarTablaSeccion( ){
 
            
             defualt.addColumn("Codigo");
             defualt.addColumn("Nombre");
             defualt.addColumn("Color");
            miTablaSeccion.setModel(defualt);
            
            String []datos=new String[3];
            try{
                Statement leer=conect.createStatement();
                ResultSet resultado=leer.executeQuery("SELECT * FROM seccion");
                
                while(resultado.next()){
                    datos[0]=resultado.getString(1);
                    datos[1]=resultado.getString(2);
                    datos[2]=resultado.getString(3);
                    defualt.addRow(datos);
                }
                miTablaSeccion.setModel(defualt);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la consulta");
        }
     
    }
        
    public void vaciarTabla(){
         while (defualt.getRowCount() > 0) {
            defualt.removeRow(0);
       }
        while(defualt.getColumnCount()>0){
     defualt.setColumnCount(defualt.getColumnCount() - 1);
        }
     }
    
    public void limpiar(){
        txtCodigo.setText("");
        txtNombre.setText("");
        txtColor.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeccionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeccionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeccionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeccionFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeccionFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblIntroduccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable miTablaSeccion;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
