/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RegistroYLogueo;


import contenidoInventario.MarcaFrm;
import contenidoInventario.ProductoFrm;
import contenidoInventario.ProveedorFrm;
import contenidoInventario.SeccionFrm;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.FondoPanel;
import modelo.Producto;
import modelo.Usuario;



/**
 *
 * @author mario
 */
public class Home extends javax.swing.JFrame {

    Usuario mod;
    Image imagen;
    FondoPanel fondo=new FondoPanel();
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
       
    }

    public Home(Usuario mod){
       this.setContentPane(fondo);
          initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRol = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnProducto = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnMarca = new javax.swing.JButton();
        btnSeccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 142, 153, 44));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("OUTFIT STOCK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 241, 45));

        btnProducto.setText("Producto");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, 30));

        btnProveedor.setText("Proveedor");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 170, 30));

        btnMarca.setText("Marca");
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 30));

        btnSeccion.setText("Seccion");
        btnSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
       
        int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres entrar a la ventana producto?","Producto",JOptionPane.OK_CANCEL_OPTION);
        switch(opcion){
            case 0:System.out.println("Presionaste el boton aceptar");
          ProductoFrm ventanaProductos=new ProductoFrm();
        this.setVisible(false);
        ventanaProductos.setVisible(true);
        break;
            case 1: System.out.println("Presionaste el boton cancelar");
            break;
        }
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
       
        int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres entrar a la ventana proveedor?","Proveedor",JOptionPane.OK_CANCEL_OPTION);
        switch(opcion){
            case 0: System.out.println("Presionaste el boton aceptar");
                 ProveedorFrm ventanaProveedor=new ProveedorFrm();
        this.setVisible(false);
        ventanaProveedor.setVisible(true);
        break;
        case 1: System.out.println("Presionaste el boton cancelar");
            break;
        }
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        
        int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres entrar a la ventana marca?","Marca",JOptionPane.OK_CANCEL_OPTION);
        switch(opcion){
            case 0: System.out.println("Presionaste el boton aceptar");
               MarcaFrm ventanaMarca=new MarcaFrm();
        this.setVisible(false);
        ventanaMarca.setVisible(true);
        break;
        case 1: System.out.println("Presionaste el boton cancelar");
            break;
        }
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeccionActionPerformed
         int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres entrar a la ventana sección?","Sección",JOptionPane.OK_CANCEL_OPTION);
        switch(opcion){
            case 0: System.out.println("Presionaste el boton aceptar");
               SeccionFrm ventanaSeccion=new SeccionFrm();
       this.setVisible(false);
        ventanaSeccion.setVisible(true);
        break;
        case 1: System.out.println("Presionaste el boton cancelar");
            break;
    }//GEN-LAST:event_btnSeccionActionPerformed
    }
    /*public void paint(Graphics g){
        Dimension tamanio=getSize();
        imagen=new ImageIcon(getClass().getResource("/imagenes/imagenesFondo.png")).getImage();
        g.drawImage(imagen,0,0,tamanio.width,tamanio.height,this);
        super.paint(g);
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarca;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRol;
    // End of variables declaration//GEN-END:variables
}
